 
import type { Metadata } from "next";
import ReduxProvider from "./ReduxProvider";
import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Header from './components/Header'
import Footer from './components/Footer'
import RouteGuard from "./components/RouteGuard";
 
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['400', '500', '700'],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
        <body
          className={`  ${roboto.variable} ${poppins.variable} antialiased`}
        >
          <ReduxProvider>
            <RouteGuard> 
              <Header />
              {children}
              <Footer />
            </RouteGuard>
          </ReduxProvider>
        </body>
      </html>
  );
}
